### ISSUE TITLE
Partial file list

### ISSUE THREAD

**Issue by Xeeynamo** [Nenkai/FF16Pack#4]
I dumped a list of file paths. It will be much more useful to you than having it sitting in my computer.

[ff16_paths.txt](https://github.com/user-attachments/files/16688579/ff16_paths.txt)

I dumped them via `strings -n 6 0000.pac | grep -E '^[a-z][a-z]+/[a-zA-Z0-9]+'` and `strings -n 6 ffxvi_demo.exe | grep -E '^[a-z][a-z]+/[a-zA-Z0-9]+'` and then cleaned up the output.

Some paths have `sprintf` formatting stuff like `%04u` or `%s`. I purposely left them in the list in case we want to brute-force them. Unfortunately the hashing algorithm doesn't play nice with bruteforcing as there are plenty of collisions happening.

**Comment by Nenkai** [comment]
File names are included in the packed files (surprisingly).

**Comment by Xeeynamo** [comment]
Oh that's really good lol . I was not yet able to extract any of the files that has the `0x201` or `0x301` storage type, and using your tool on Linux doesn't currently work, so I did not know. That's actually good news then!
